### ISSUE TITLE
No hljs class, or a way to define language

### ISSUE THREAD

**Issue by dcorb** [johannestroeger/gulp-highlight#4]
This gulp plugin calls `highlightAuto`, instead of `highlightBlock`

That means, that:
- `hljs` class is not added to the code block. (highlight themes not fully applied, specially background colors)
- no way of specifying a language via the class of the code block.

I don't see easy solution. `highlightBlock` needs access to some DOM attributes that are not implemented by cheerio, like textContent.

https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L568

Should we add some line of codes to simulate in cheerio what highlightBlock does to the `<code>` wrapper ?

**Comment by johannestroeger** [comment]
hey, there. thanks for submitting that issue, i was not really aware of. 

- `hljs` class not added. i think you have to add it by yourself. 
- defining a language is done by passing the option languageSubset, even with `highlightAuto` see: https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L503

would you like to add a PR for that?

**Comment by johannestroeger** [comment]
@dcorb currently in #5 @jsmiff is implementing a configurable version of this plugin. maybe you team-up to get the `languageSubset` enabled/disabled as option.

**Comment by dcorb** [comment]
Would you like I submit a PR for adding the "hljs" class ? 

About the languageSubset, it's only for limiting a subset of languages.. but still you are relying on autodetection.

I would like to use this plugin in a similar fashion than highlight js in the client-side, by specifying a language CSS class in the <code> tag.

After saying this.. still, I could work on a languageSubset option, after @jsmiff PR goes in. It should improve the auto-detection, I guess.

**Comment by johannestroeger** [comment]
great. looking forward to it!

**Comment by johannestroeger** [comment]
@dcorb you could start? #5 is merged.
