### ISSUE TITLE
The package eslint@1.10.3 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by YuxinChou** [johannestroeger/gulp-highlight#8]
Hi，when I try to install it, there are some error...

The package eslint@1.10.3 does not satisfy its siblings' peerDependencies requirements!

> npm WARN unmet dependency /Users/mrain/Desktop/gulpT/node_modules/gulp-file-include/node_modules/markdown/node_modules/nopt/node_modules/abbrev/node_modules/tap/node_modules/glob,
npm WARN unmet dependency which is version 7.0.5
npm WARN unmet dependency /Users/mrain/Desktop/gulpT/node_modules/gulp-file-include/node_modules/markdown/node_modules/tap/node_modules/buffer-equal/node_modules/tap requires nopt@'~1.0.10' but will load
npm WARN unmet dependency /Users/mrain/Desktop/gulpT/node_modules/gulp-file-include/node_modules/markdown/node_modules/nopt,
npm WARN unmet dependency which is version 2.1.2
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "gulp-highlight"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package eslint@1.10.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mrain/Desktop/gulpT/npm-debug.log

I used these in my project
---
    "gulp": "^3.9.1",
    "gulp-compass": "^2.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-html-extend": "^1.1.6",
    "gulp-html-replace": "^1.6.1",
    "gulp-markdown": "^1.2.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-minify-html": "^1.0.6",
    "gulp-rename": "^1.2.2",
    "gulp-uglify": "^1.5.4",
    "gulp-webserver": "^0.9.1"
---

how to fix it?
Thank you.

**Comment by junajan** [comment]
Please add also comment how to fix it ..
